STEP_1:
  input:
    type: read_local
    target: parameter_x_formula

STEP_2:
  input:
    type: read_local
    target: parameter_x_formula_schema

STEP_3:
  data_validation:
    calibrate: step_1
    schema: step_2