STEP_1:
  input:
    type: read_local
    target: requirement_x_parameter

STEP_2:
  input:
    type: read_local
    target: requirement_x_parameter_schema

STEP_3:
  data_validation:
    calibrate: step_1
    schema: step_2