STEP_1:
  input:
    type: read_local
    target: statusXcolor

STEP_2:
  input:
    type: read_local
    target: statusXcolor_schema

STEP_3:
  data_validation:
    calibrate: step_1
    schema: step_2