STEP_1:
  input: status_x_color
    type: read_local
    target:

STEP_2:
  input: status_x_color_schema
    type: read_local
    target:

STEP_3:
  data_validation:
    calibrate: step_1
    schema: step_2