STEP_1:
  input:
    type: read_local
    target: visualizer_parameters

STEP_2:
  input:
    type: read_local
    target: visualizer_parameters_schema

STEP_3:
  data_validation:
    calibrate: step_1
    schema: step_2