STEP_1:
  component:
    comp_name: parameter_connections

STEP_2:
  component:
    comp_name: parameter_x_field

STEP_3:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_1
      right_df: step_2
      join_type: inner
      join_cols:
        - PARXXXXX_id
    save_step:
      save_name: join_1.csv

STEP_4:
  component:
    comp_name: parameter_connections