STEP_1:
  component:
    comp_name: parent_x_parameter

STEP_2:
  component:
    comp_name: parameter_x_field

STEP_3:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_1
      right_df: step_2
      join_type: left
      join_cols:
        - PARXXXXX_id

STEP_4:
  component:
    comp_name: requirement_x_parameter

STEP_5:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_3
      right_df: step_4
      join_type: left
      join_cols:
        - PARXXXXX_id
    save_step:
      save_name: abc_test_save.csv

STEP_6:
  component:
    comp_name: parameter_x_formula

STEP_7:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_5
      right_df: step_6
      join_type: left
      join_cols:
        - PARXXXXX_id

STEP_8:
  component:
    comp_name: status_x_color

STEP_9:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_7
      right_df: step_8
      join_type: left
      join_cols:
        - PARXXXXX_id

STEP_10:
  component:
    comp_name: parameter_connections

STEP_11:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_9
      right_df: step_10
      join_type: left
      join_cols:
        - PARXXXXX_id

STEP_12:
  component:
    comp_name: parameter_x_values

STEP_13:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_11
      right_df: step_12
      join_type: left
      join_cols:
        - PARXXXXX_id

STEP_14:
  component:
    comp_name: parameter_x_description

STEP_15:
  dataframes_interaction:
    type: merge
    parameters:
      left_df: step_13
      right_df: step_14
      join_type: left
      join_cols:
        - PARXXXXX_id

# STEP_12:
#   fill_na:
#     subset:
#       set_value:
#         "unknown":
#           - FORXXXXX_used
#           - status
#         "#FFB8B8":
#           - fill_color

# STEP_13:
#   generate_xml:
#     target: visualizer_parameters